### ISSUE TITLE
FuseSource repo seems to be down , not able to build

### ISSUE THREAD

**Issue by ABHINAVKR** [satyagraha/logviewer#4]
@satyagraha 
![screenshot from 2016-01-10 17 05 15](https://cloud.githubusercontent.com/assets/6654024/12221328/593571cc-b7bc-11e5-970e-dc64b22c4c88.png)

**Comment by vitordepaula** [comment]
+1 to this

**Comment by satyagraha** [comment]
Looks OK now:

> [INFO] ------------------------------------------------------------------------
> [INFO] Building logviewer 0.0.4-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> Downloading: http://mvnplugins.fusesource.org/repo/release/org/fusesource/mvnplugins/maven-graph-plugin/1.29/maven-graph-plugin-1.29.pom
> Downloading: http://repo.maven.apache.org/maven2/org/fusesource/mvnplugins/maven-graph-plugin/1.29/maven-graph-plugin-1.29.pom
> Downloaded: http://repo.maven.apache.org/maven2/org/fusesource/mvnplugins/maven-graph-plugin/1.29/maven-graph-plugin-1.29.pom (3 KB at 8.1 KB/sec)
> Downloading: http://mvnplugins.fusesource.org/repo/release/org/fusesource/mvnplugins/mvnplugins/1.29/mvnplugins-1.29.pom
> Downloading: http://repo.maven.apache.org/maven2/org/fusesource/mvnplugins/mvnplugins/1.29/mvnplugins-1.29.pom
> Downloaded: http://repo.maven.apache.org/maven2/org/fusesource/mvnplugins/mvnplugins/1.29/mvnplugins-1.29.pom (9 KB at 41.0 KB/sec)
> Downloading: http://mvnplugins.fusesource.org/repo/release/org/fusesource/mvnplugins/maven-graph-plugin/1.29/maven-graph-plugin-1.29.jar
> Downloading: http://repo.maven.apache.org/maven2/org/fusesource/mvnplugins/maven-graph-plugin/1.29/maven-graph-plugin-1.29.jar
> Downloaded: http://repo.maven.apache.org/maven2/org/fusesource/mvnplugins/maven-graph-plugin/1.29/maven-graph-plugin-1.29.jar (23 KB at 44.8 KB/sec)
> [INFO]
